name: Module release

on:
  push:
    tags: ['v*.*.*']

jobs:
  release:
    uses: DavidMRGaona/runesword/.github/workflows/reusable-module-release.yml@main
    with:
      module_name: 'tournaments'
    permissions:
      contents: write
